### PR TITLE
feat(Canvas): add support for displaying output in Jupyter Notebook

### PR DESCRIPTION
**Pull request by DjDeveloperr**

### CODE REVIEW

**Comment by rgbkrk** [comment]
Giving your branch a spin now to see if I can find the issue you mentioned on discord.

**Comment by rgbkrk** [comment]
Well I got it to work and it must be a TypeScript or Deno quirk. If you bind it in the constructor then the Deno kernel picks it up:

```typescript
  constructor(width: number, height: number, gpu = false) {
    this[$display] = this[$display].bind(this);
```

image

**Comment by bartlomieju** [comment]
Could you point me which one is not working here? Is it `canvas.ts` or `svgcanvas.ts`?

**Comment by DjDeveloperr** [comment]
> Could you point me which one is not working here? Is it `canvas.ts` or `svgcanvas.ts`?

@bartlomieju it's `canvas.ts`

**Comment by bartlomieju** [comment]
Thanks, I'll try to take a look ASAP.

**Comment by bartlomieju** [comment]
I just tried this and I got:
Screenshot 2023-09-23 at 10 22 58

I think this is related to https://github.com/denoland/deno/issues/20528

**Comment by bartlomieju** [comment]
So the underlying issue is that this error is raised:
```
TypeError: Cannot read properties of undefined (reading 'encode')\n    at [Jupyter.display] (file:///Users/ib/dev/skia_canvas/src/canvas.ts:215:38)\n    at <anonymous>:4:33
```
However I don't yet understand why that's the case. The transpiled output looks correct and AFAIK `this` should be the class intance in this case. I will consult with the team and get back to you.

**Comment by rgbkrk** [comment]
The bug causing it to not render properly has been fixed: https://github.com/denoland/deno/pull/20789

image

I had to jump to https://github.com/denoland/deno/commit/cbddf5756e07fbbe10bd35d23bb9e9c0c685442a to make it work though because deno `main` can't load this module right now (#61).

**Review by rgbkrk — APPROVED** [review]

**Comment by DjDeveloperr** [comment]
Awesome fix @rgbkrk - I'll cut a release once that fix makes it to stable.

**Comment by rgbkrk** [comment]
The fix for ffi is on `main`.

**Comment by rgbkrk** [comment]
1.37.2 is out with the fix, feel free to ship 🚢

**Comment by DjDeveloperr** [comment]
I've released 0.5.5:

image

**Pull request merged**
